GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test9",
  "author": "Test9",
  "url": "Test9",
  "user_id": "67cd9d6acdc1ee561e9b5086"
}