GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaXIiLCJpZCI6IjY3ZDA4NGRjMTVlOGExNDkzZGE2MjU2NiIsImlhdCI6MTc0MjEzNjI2OX0.BRhFt1A7Ko56pc2RoeRg19CL87UstupvtYwuqr_-fyI

{
  "title": "Test9",
  "author": "Test7",
  "url": "Test9"
}

###
DELETE http://localhost:3003/api/blogs/67d6e1a51369f97555fab233
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaXIiLCJpZCI6IjY3ZDA4NGRjMTVlOGExNDkzZGE2MjU2NiIsImlhdCI6MTc0MjEzNjI2OX0.BRhFt1A7Ko56pc2RoeRg19CL87UstupvtYwuqr_-fyI