GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test8",
  "author": "Test8",
  "url": "Test8",
  "user": "67ccb9766dd8771b7022a241"
}